from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm 
from sqlmodel import Session, select
from app.db.session import get_session
from app.models.auth import User, Student, Company, UserRole
from app.schemas import UserCreate, UserPublic, Token
from app.core.security import get_password_hash, verify_password, create_access_token, create_refresh_token
from app.core.config import settings
from datetime import timedelta
from app.api.deps import get_current_user

router = APIRouter()

@router.post("/register", response_model=UserPublic)
def register_user(user_in: UserCreate, session: Session = Depends(get_session)):
    """
    Register a new user.
    1. Check if email exists.
    2. Hash password.
    3. Create User.
    4. Create associated Student/Company profile.
    """
    
    # 1. Check if email already exists
    statement = select(User).where(User.email == user_in.email)
    existing_user = session.exec(statement).first()
    if existing_user:
        raise HTTPException(status_code=400, detail="Email already registered")

    # 2. Create the User Object
    hashed_pwd = get_password_hash(user_in.password)
    new_user = User(
        email=user_in.email,
        password_hash=hashed_pwd,
        role=user_in.role
    )
    session.add(new_user)
    session.commit()
    session.refresh(new_user) # Get the ID generated by DB

    # 3. Create the Profile (Student or Company)
    if user_in.role == UserRole.STUDENT:
        new_profile = Student(
            user_id=new_user.id,
            full_name=user_in.full_name
        )
        session.add(new_profile)
    
    elif user_in.role == UserRole.COMPANY:
        new_profile = Company(
            user_id=new_user.id,
            company_name=user_in.full_name, # Using full_name as company name for now
            location="Not provided"
        )
        session.add(new_profile)

    session.commit()

    return new_user

@router.post("/token", response_model=Token)
def login_for_access_token(
    form_data: OAuth2PasswordRequestForm = Depends(),
    session: Session = Depends(get_session)
):
    """
    Logs in a user.
    Note: OAuth2 spec uses 'username', but we treat it as 'email'.
    """
    
    # 1. Find user by email
    statement = select(User).where(User.email == form_data.username)
    user = session.exec(statement).first()
    
    # 2. Check if user exists AND password is correct
    if not user or not verify_password(form_data.password, user.password_hash):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect email or password",
            headers={"WWW-Authenticate": "Bearer"},
        )
    
    # 3. Create JWT Tokens (Access + Refresh)
    access_token_expires = timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)
    access_token = create_access_token(
        data={"sub": user.email, "role": user.role.value, "id": user.id},
        expires_delta=access_token_expires
    )
    
    refresh_token_expires = timedelta(days=settings.REFRESH_TOKEN_EXPIRE_DAYS)
    refresh_token = create_refresh_token(
        data={"sub": user.email, "role": user.role.value, "id": user.id},
        expires_delta=refresh_token_expires
    )
    
    # 4. Return both tokens
    return {
        "access_token": access_token,
        "refresh_token": refresh_token,
        "token_type": "bearer"
    }

@router.post("/refresh", response_model=Token)
def refresh_access_token(
    refresh_token: str,
    session: Session = Depends(get_session)
):
    """
    Get a new access token using a valid refresh token.
    """
    from jose import JWTError, jwt
    
    try:
        # 1. Decode the refresh token
        payload = jwt.decode(refresh_token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
        email: str = payload.get("sub")
        token_type: str = payload.get("type")
        
        # 2. Verify it's a refresh token
        if email is None or token_type != "refresh":
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid refresh token",
                headers={"WWW-Authenticate": "Bearer"},
            )
        
        # 3. Find user by email
        statement = select(User).where(User.email == email)
        user = session.exec(statement).first()
        
        if not user:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="User not found",
                headers={"WWW-Authenticate": "Bearer"},
            )
        
        # 4. Create new access token
        access_token_expires = timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)
        new_access_token = create_access_token(
            data={"sub": user.email, "role": user.role.value, "id": user.id},
            expires_delta=access_token_expires
        )
        
        # 5. Return new access token (keep same refresh token)
        return {
            "access_token": new_access_token,
            "refresh_token": refresh_token,
            "token_type": "bearer"
        }
        
    except JWTError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Could not validate refresh token",
            headers={"WWW-Authenticate": "Bearer"},
        )

@router.get("/me", response_model=UserPublic)
def read_users_me(current_user: User = Depends(get_current_user)):
    """
    Get current user details with their name and profile image.
    """
    from app.core.supabase import supabase
    
    # 1. Determine the name and profile image based on Role
    display_name = None
    company_profile_id = None
    profile_image_url = None
    
    if current_user.role == UserRole.STUDENT:
        # Check if profile exists to avoid crash
        if current_user.student_profile:
            display_name = current_user.student_profile.full_name
            # Get profile image URL
            if current_user.student_profile.profile_image_url:
                try:
                    path = current_user.student_profile.profile_image_url
                    res = supabase.storage.from_("profile-images").create_signed_url(path, 3600)
                    if isinstance(res, dict) and "signedURL" in res:
                        profile_image_url = res["signedURL"]
                    elif isinstance(res, str):
                        profile_image_url = res
                except Exception as e:
                    print(f"Error generating profile image signed URL: {e}")
            
    elif current_user.role == UserRole.COMPANY:
        if current_user.company_profile:
            # For companies, we use company_name as the full_name
            display_name = current_user.company_profile.company_name
            company_profile_id = current_user.company_profile.id
            # Get profile image URL
            if current_user.company_profile.profile_image_url:
                try:
                    path = current_user.company_profile.profile_image_url
                    res = supabase.storage.from_("profile-images").create_signed_url(path, 3600)
                    if isinstance(res, dict) and "signedURL" in res:
                        profile_image_url = res["signedURL"]
                    elif isinstance(res, str):
                        profile_image_url = res
                except Exception as e:
                    print(f"Error generating profile image signed URL: {e}")

    # 2. Return the data matching the UserPublic schema
    return UserPublic(
        id=current_user.id,
        email=current_user.email,
        role=current_user.role,
        full_name=display_name,
        company_profile_id=company_profile_id,
        profile_image_url=profile_image_url
    )