apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: campuscareerai-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - campuscareerai.me
        - www.campuscareerai.me
        - api.campuscareerai.me
      secretName: campuscareerai-tls

  rules:
    - host: campuscareerai.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80

    - host: api.campuscareerai.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80