"""Added resume_url to students

Revision ID: 4950c2d94e53
Revises: ff8c6bc011f4
Create Date: 2025-11-29 02:22:40.942011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4950c2d94e53'
down_revision: Union[str, Sequence[str], None] = 'ff8c6bc011f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('resume_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'resume_url')
    # ### end Alembic commands ###
