"""Added deadline to jobs

Revision ID: 89fbb778d3a5
Revises: 00d4e7139d7a
Create Date: 2025-12-07 11:00:44.333116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '89fbb778d3a5'
down_revision: Union[str, Sequence[str], None] = '00d4e7139d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'deadline')
    # ### end Alembic commands ###
