"""Added ON DELETE CASCADE to foreign keys

Revision ID: b78f026bd610
Revises: 9bf3b95a36c7
Create Date: 2025-12-23 12:32:11.764524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b78f026bd610'
down_revision: Union[str, Sequence[str], None] = '9bf3b95a36c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('applications_job_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_student_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('companies_user_id_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('job_views_user_id_fkey'), 'job_views', type_='foreignkey')
    op.drop_constraint(op.f('job_views_job_id_fkey'), 'job_views', type_='foreignkey')
    op.create_foreign_key(None, 'job_views', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'job_views', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('jobs_company_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('saved_jobs_job_id_fkey'), 'saved_jobs', type_='foreignkey')
    op.drop_constraint(op.f('saved_jobs_user_id_fkey'), 'saved_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'saved_jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'saved_jobs', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('students_user_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_user_id_fkey'), 'students', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'saved_jobs', type_='foreignkey')
    op.drop_constraint(None, 'saved_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('saved_jobs_user_id_fkey'), 'saved_jobs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('saved_jobs_job_id_fkey'), 'saved_jobs', 'jobs', ['job_id'], ['id'])
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_company_id_fkey'), 'jobs', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'job_views', type_='foreignkey')
    op.drop_constraint(None, 'job_views', type_='foreignkey')
    op.create_foreign_key(op.f('job_views_job_id_fkey'), 'job_views', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(op.f('job_views_user_id_fkey'), 'job_views', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_user_id_fkey'), 'companies', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_student_id_fkey'), 'applications', 'students', ['student_id'], ['id'])
    op.create_foreign_key(op.f('applications_job_id_fkey'), 'applications', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###
